name: yogicast
description: AI-powered podcast creation platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  dio: ^5.3.2
  uuid: ^4.0.0
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.1
  just_audio: ^0.9.36
  audio_session: ^0.1.18
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
